<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DL54W4WV2" failures="1" tests="10" name="Group 4" time="0.409" errors="0" timestamp="2022-09-28T14:03:03 ICT">
  <testcase classname="test.testng01.testng.TestNGHook01" name="testSth" time="0.092"/>
  <testcase classname="test.testng01.testng.TestNGHook01" name="testSthElse" time="0.004"/>
  <testcase classname="test.testng01.testng.TestNGHook02" name="testSth" time="0.001"/>
  <testcase classname="test.testng01.testng.TestNGHook02" name="testSthElse" time="0.006"/>
  <testcase classname="test.testng.TestNGHook01" name="testSth" time="0.001"/>
  <testcase classname="test.testng.TestNGHook01" name="testSthElse" time="0.001"/>
  <testcase classname="test.testng.TestNGHook02" name="testSth" time="0.002"/>
  <testcase classname="test.testng.TestNGHook02" name="testSthElse" time="0.001"/>
  <testcase classname="test.testng.TestNGTestOrder" name="test01" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test.testng.TestNGTestOrder.test01(TestNGTestOrder.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- test01 -->
  <testcase classname="test.testng.TestNGTestOrder" name="test02" time="0.0">
    <skipped/>
  </testcase> <!-- test02 -->
</testsuite> <!-- Group 4 -->
